#ifndef __LEX_H__
#define __LEX_H__
#include <stdio.h>

enum lex_token_type
{
	LEX_TOKEN_TYPE_EOF = 0,
	LEX_TOKEN_TYPE_BITWISE_NOT   = '~',
	LEX_TOKEN_TYPE_MODULO        = '%',
	LEX_TOKEN_TYPE_BITWISE_XOR   = '^',
	LEX_TOKEN_TYPE_BITWISE_AND   = '&',
	LEX_TOKEN_TYPE_MULTIPLY      = '*',
	LEX_TOKEN_TYPE_SUBTRACT      = '-',
	LEX_TOKEN_TYPE_ADD           = '+',
	LEX_TOKEN_TYPE_BITWISE_OR    = '|',
	LEX_TOKEN_TYPE_LESS_THAN     = '<',
	LEX_TOKEN_TYPE_GREATER_THAN  = '>',
	LEX_TOKEN_TYPE_ASSIGN        = '=',
	LEX_TOKEN_TYPE_LOGICAL_NOT   = '!',
	LEX_TOKEN_TYPE_TERTIARY      = '?',
	LEX_TOKEN_TYPE_PERIOD        = '.',
	LEX_TOKEN_TYPE_COMMA         = ',',
	LEX_TOKEN_TYPE_SEMICOLON     = ';',
	LEX_TOKEN_TYPE_COLON         = ':',
	LEX_TOKEN_TYPE_OPEN_PAREN    = '(',
	LEX_TOKEN_TYPE_CLOSE_PAREN   = ')',
	LEX_TOKEN_TYPE_OPEN_SQUARE   = '[',
	LEX_TOKEN_TYPE_CLOSE_SQUARE  = ']',
	LEX_TOKEN_TYPE_OPEN_BRACKET  = '{',
	LEX_TOKEN_TYPE_CLOSE_BRACKET = '}',
	LEX_TOKEN_TYPE_HASH          = '#',
	LEX_TOKEN_TYPE_UNKNOWN       = 0xff,
	LEX_TOKEN_TYPE_SHIFT_LEFT,
	LEX_TOKEN_TYPE_ROLL_LEFT,
	LEX_TOKEN_TYPE_SHIFT_RIGHT,
	LEX_TOKEN_TYPE_ROLL_RIGHT,
	LEX_TOKEN_TYPE_ASSIGN_BITWISE_NOT,
	LEX_TOKEN_TYPE_NOT_EQUATE,
	LEX_TOKEN_TYPE_ASSIGN_MODULO,
	LEX_TOKEN_TYPE_ASSIGN_BITWISE_XOR,
	LEX_TOKEN_TYPE_ASSIGN_BITWISE_AND,
	LEX_TOKEN_TYPE_ASSIGN_MULTIPLY,
	LEX_TOKEN_TYPE_ASSIGN_SUBTRACT,
	LEX_TOKEN_TYPE_ASSIGN_ADD,
	LEX_TOKEN_TYPE_ASSIGN_BITWISE_OR,
	LEX_TOKEN_TYPE_ASSIGN_SHIFT_LEFT,
	LEX_TOKEN_TYPE_ASSIGN_ROLL_LEFT,
	LEX_TOKEN_TYPE_ASSIGN_SHIFT_RIGHT,
	LEX_TOKEN_TYPE_ASSIGN_ROLL_RIGHT,
	LEX_TOKEN_TYPE_LOGICAL_AND,
	LEX_TOKEN_TYPE_LOGICAL_OR,
	LEX_TOKEN_TYPE_LESS_THAN_OR_EQUAL,
	LEX_TOKEN_TYPE_GREATER_THAN_OR_EQUAL,
	LEX_TOKEN_TYPE_EQUATE,
	LEX_TOKEN_TYPE_INCREMENT,
	LEX_TOKEN_TYPE_DECREMENT,
	LEX_TOKEN_TYPE_MEMBER,
	LEX_TOKEN_TYPE_ALIGNAS,
	LEX_TOKEN_TYPE_ALIGNOF,
	LEX_TOKEN_TYPE_ATOMIC,
	LEX_TOKEN_TYPE_BITINT,
	LEX_TOKEN_TYPE_COMPLEX,
	LEX_TOKEN_TYPE_COUNTOF,
	LEX_TOKEN_TYPE_DECIMAL32,
	LEX_TOKEN_TYPE_DECIMAL64,
	LEX_TOKEN_TYPE_DECIMAL128,
	LEX_TOKEN_TYPE_GENERIC,
	LEX_TOKEN_TYPE_NORETURN,
	LEX_TOKEN_TYPE_IMAGINARY,
	LEX_TOKEN_TYPE_PRAGMA,
	LEX_TOKEN_TYPE_AUTO,
	LEX_TOKEN_TYPE_BOOL,
	LEX_TOKEN_TYPE_BREAK,
	LEX_TOKEN_TYPE_CASE,
	LEX_TOKEN_TYPE_CHAR,
	LEX_TOKEN_TYPE_CONST,
	LEX_TOKEN_TYPE_CONSTEXPR,
	LEX_TOKEN_TYPE_CONTINUE,
	LEX_TOKEN_TYPE_DEFAULT,
	LEX_TOKEN_TYPE_DO,
	LEX_TOKEN_TYPE_DOUBLE,
	LEX_TOKEN_TYPE_ELSE,
	LEX_TOKEN_TYPE_ENUM,
	LEX_TOKEN_TYPE_EXTERN,
	LEX_TOKEN_TYPE_FLOAT,
	LEX_TOKEN_TYPE_FOR,
	LEX_TOKEN_TYPE_GOTO,
	LEX_TOKEN_TYPE_IF,
	LEX_TOKEN_TYPE_INLINE,
	LEX_TOKEN_TYPE_INT,
	LEX_TOKEN_TYPE_LONG,
	LEX_TOKEN_TYPE_REGISTER,
	LEX_TOKEN_TYPE_RESTRICT,
	LEX_TOKEN_TYPE_RETURN,
	LEX_TOKEN_TYPE_SHORT,
	LEX_TOKEN_TYPE_SIGNED,
	LEX_TOKEN_TYPE_SIZEOF,
	LEX_TOKEN_TYPE_STATIC,
	LEX_TOKEN_TYPE_STATIC_ASSERT,
	LEX_TOKEN_TYPE_STRUCT,
	LEX_TOKEN_TYPE_SWITCH,
	LEX_TOKEN_TYPE_THREAD_LOCAL,
	LEX_TOKEN_TYPE_TYPEDEF,
	LEX_TOKEN_TYPE_TYPEOF,
	LEX_TOKEN_TYPE_TYPEOF_UNQUAL,
	LEX_TOKEN_TYPE_UNION,
	LEX_TOKEN_TYPE_UNSIGNED,
	LEX_TOKEN_TYPE_VOID,
	LEX_TOKEN_TYPE_VOLATILE,
	LEX_TOKEN_TYPE_WHILE,
	LEX_TOKEN_TYPE_NULLPTR,
	LEX_TOKEN_TYPE_TRUE,
	LEX_TOKEN_TYPE_FALSE,
	LEX_TOKEN_TYPE_HASH_IF,
	LEX_TOKEN_TYPE_HASH_ELIF,
	LEX_TOKEN_TYPE_HASH_ELSE,
	LEX_TOKEN_TYPE_HASH_ENDIF,
	LEX_TOKEN_TYPE_HASH_IFDEF,
	LEX_TOKEN_TYPE_HASH_IFNDEF,
	LEX_TOKEN_TYPE_HASH_ELIFDEF,
	LEX_TOKEN_TYPE_HASH_ELIFNDEF,
	LEX_TOKEN_TYPE_HASH_DEFINE,
	LEX_TOKEN_TYPE_HASH_UNDEF,
	LEX_TOKEN_TYPE_HASH_INCLUDE,
	LEX_TOKEN_TYPE_HASH_EMBED,
	LEX_TOKEN_TYPE_HASH_LINE,
	LEX_TOKEN_TYPE_HASH_ERROR,
	LEX_TOKEN_TYPE_HASH_WARNING,
	LEX_TOKEN_TYPE_HASH_PRAGMA,
	LEX_TOKEN_TYPE_HASH_HAS_INCLUDE,
	LEX_TOKEN_TYPE_HASH_HAS_EMBED,
	LEX_TOKEN_TYPE_HASH_HAS_C_ATTRIBUTE,
	LEX_TOKEN_TYPE_COMMENT,
	LEX_TOKEN_TYPE_SYMBOL,
	LEX_TOKEN_TYPE_LITERAL_INTEGER,
	LEX_TOKEN_TYPE_LITERAL_FLOAT,
	LEX_TOKEN_TYPE_LITERAL_CHARACTER,
	LEX_TOKEN_TYPE_LITERAL_STRING,
	LEX_TOKEN_TYPE_WHITESPACE
};

struct lex_token
{
	enum lex_token_type type;

	char *buf;   // the buffer
	long  bufcp; // the buffer capacity
	long  bufsz; // the buffer size
};

/**
 * The current lexer token
 * @file lex/enter.c
 */
extern struct lex_token lex_token;

struct lex_context
{
	FILE       *fp;
	const char *path;
	long        lineno;
	long        offset;
	long        size;
};

/**
 * The lexer file context
 * @file lex/enter.c
 */
extern struct lex_context lex_context;

/**
 * Enter a new lexer context
 * @param path The file path
 * @param fp The file pointer
 * @file lex/enter.c
 */
extern void lex_enter (const char *path, FILE *fp);

/**
 * Free all lexer associated data
 * @file lex/free.c
 */
extern void lex_free (void);

#endif
