name: Build
on: [push]
jobs:
    Build:
        runs-on: self-hosted
        steps:
            - name: "Check out"
              run: actions/checkout@v4
            - name: "Configure"
              run: "yes \"\" | ./oldconfig"
            - name: "Build"
              run: "tup"
